Zadanie2: Zadanie2.cpp
	g++ -o Zadanie2 Zadanie2.cpp

Zadanie1: Zadanie1.cpp
	g++ -o Zadanie1 Zadanie1.cpp


Zadanie5: Zadanie5.cpp 
	g++ -o Zadanie5 Zadanie5.cpp

Zadanie3: Zadanie3.cpp
	g++ -o Zadanie3 Zadanie3.cpp

Zadanie8: Zadanie8.cpp
	g++ -o Zadanie8 Zadanie8.cpp
