package ListaMV;

import KonwersjaDanych.KonwerterGCalend;

import javax.swing.*;
import java.awt.*;
import java.util.*;

public class ListaM extends AbstractListModel {


    private String[] Data;


    private JPanel panel1;
    private int Year;
    private int Month;

    public ListaM(int year, int month) {
        Year = year;
        Month = month;

    }

    public void add() {
        if (Year == 1582 && Month == 9)
            addOct1582();
        else {
            GregorianCalendar buf = new GregorianCalendar(Year, Month, 1);
            Data = new String[buf.getActualMaximum(Calendar.DAY_OF_MONTH)];

            for (int i = 0; i < getSize(); i++) {

                Data[i] = "";
                buf.set(Year, Month, i + 1);
                Data[i] += i + 1 + " " + KonwerterGCalend.NumbToDayOfWeek(buf.get(Calendar.DAY_OF_WEEK));
            }

            fireContentsChanged(this, 0, getSize() - 1);
        }
    }

    private void addOct1582() {
        GregorianCalendar buf = new GregorianCalendar(Year, Month, 1);
        Data = new String[buf.getActualMaximum(Calendar.DAY_OF_MONTH) - 10];
        int iGreg = 0;
        for (int i = 0; i < 31; i++) {

            if (i == 4) {
                i = 13;
                iGreg = 10;
                continue;
            }
            Data[i - iGreg] = "";
            buf.set(Year, Month, i + 1);
            Data[i - iGreg] += i + 1 + " " + KonwerterGCalend.NumbToDayOfWeek(buf.get(Calendar.DAY_OF_WEEK));
        }

        fireContentsChanged(this, 0, getSize() - 1);
    }

    @Override
    protected void fireContentsChanged(Object o, int i, int i1) {
        super.fireContentsChanged(o, i, i1);
    }

    @Override
    public int getSize() {
        if (Data == null)
            return 0;
        return Data.length;
    }

    @Override
    public String getElementAt(int i) {

        return Data[i];
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
